# docker compose -f compose.dev.yaml up --build

services:
  ls-img-compress:
    build:
      context: .
      args:
        - ENVIRONMENT=production # development
    environment:
      - USERNAME=test
      - PASSWORD=test
    ports:
      - "3475:80"
    restart: unless-stopped
