# Basic compose file for deploying LS IMG Compress

services:
  ls-img-compress:
    container_name: ls-img-compress
    image: ghcr.io/girishlade111/Image-Compressor:latest
    ports:
      - "3474:80"
    restart: unless-stopped
